# Generated by Django 3.2.6 on 2021-09-17 10:46

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=40)),
                ("middle_name", models.CharField(blank=True, max_length=40)),
                ("last_name", models.CharField(max_length=40)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None, unique=True
                    ),
                ),
                ("birthdate", models.DateField()),
                ("website", models.URLField(max_length=400)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Studio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40, unique=True)),
                ("website", models.URLField(max_length=400)),
                ("slug", models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40, unique=True)),
                ("subtitle", models.URLField(max_length=400)),
                ("slug", models.SlugField(max_length=200)),
                ("released_date", models.DateField()),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="images"),
                ),
                ("review", models.TextField(max_length=1000)),
                ("asin", models.IntegerField(unique=True)),
                ("directors", models.ManyToManyField(to="movies.Director")),
                (
                    "genre",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "studio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.studio"
                    ),
                ),
            ],
        ),
    ]
